### ISSUE TITLE
LF: Password for live boot

### ISSUE THREAD

**Issue by xiv3r** [Xkaliberos/Scripts#1]
I want to try before i install

![20231215_061627_default](https://github.com/Xkaliberos/Scripts/assets/117867334/25191ac1-222c-4125-8873-8748cdb462b6)

**Comment by Xkaliberos** [comment]
I think it's 0000 . Try and let me know

**Comment by espero-dev** [comment]
the password should be 0000 by default

**Comment by xiv3r** [comment]
> the password should be 0000 by default

Thank you!

**Comment by xiv3r** [comment]
> I think it's 0000 . Try and let me know

It's 0000

Thanks

**Comment by espero-dev** [comment]
> > the password should be 0000 by default
> 
> Thank you!

yea np i only remember it because me and him where chatting well he was working on it
